# Defines the goal as the target coordinate for axis
float32 target_coordinate
---
# Defines the result as a boolean telling if the axis has reached the target coordinate
bool result
---
# Defines the feedback as the current coordinate
float32 current_coordinate
